# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izNQjOrwAVAxo5Oq5yBbQe81o4GvOMjE
"""

pip install streamlit

import streamlit as st
import pandas as pd

st.write("""
# Substraction of two numbers (First_num - Second_num)
""")
#Get Input

st.header('User Input Parameters')

def user_input_features():

    First_num = st.number_input("First_num")
    Second_num = st.number_input("Seconf_num")

    return First_num, Second_num

a,b = user_input_features()



# Model Loading
clf =  a-b

#Model Inferencing

st.subheader('Value after substraction')
st.write(clf)
